server {
    listen 80;

    # Статические файлы
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Проксирование API на бэкенд
    location /api/ {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
